more memory cleanup stuff

diff --git a/rootfs/etc/services.d/cleanup/run b/rootfs/etc/services.d/cleanup/run
--- a/rootfs/etc/services.d/cleanup/run
+++ b/rootfs/etc/services.d/cleanup/run
@@ -27,7 +27,7 @@ SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd)/$(basename "$0")"
 trap 'echo -e "[$(date)][$APPNAME][ERROR] $SCRIPT_PATH in line $LINENO when executing: $BASH_COMMAND returned ${?}"' ERR
 
 APPNAME="$(hostname)/cleanup"
-echo "[$(date)][$APPNAME] Started as an s6 service"
+echo "[$(date)][$APPNAME] Starting cleanup run"
 
 renice -n 20 -p $$ >/dev/null 2>/dev/null
 
@@ -40,54 +40,51 @@ MMSI_RETENTION=1209600		# 2 weeks in seconds
 [[ -z "${VESSELDBLOCK}" ]] && VESSELDBLOCK="/run/vesseldb.lock" || true
 
 
-while true
+echo "[$(date)][$APPNAME] Starting Cleanup"
+[[ -f  $VESSELDBLOCK ]] && echo "[$(date)][$APPNAME] Waiting for vessel.db to become unlocked..."
+while [[ -f  $VESSELDBLOCK ]]
 do
-	echo "[$(date)][$APPNAME] Starting Cleanup"
-	[[ -f  $VESSELDBLOCK ]] && echo "[$(date)][$APPNAME] Waiting for vessel.db to become unlocked..."
-	while [[ -f  $VESSELDBLOCK ]]
-	do
-		sleep "0.$((RANDOM % 100))"
-	done
-	# Now lock the process for myself:
-	touch "$VESSELDBLOCK"
+	sleep "0.$((RANDOM % 100))"
+done
+# Now lock the process for myself:
+touch "$VESSELDBLOCK"
 
 #	echo -n "[$(date)][$APPNAME] Removing obsolete screenshots; " && find /data/imagecache/screenshots -maxdepth 1 -mmin +${SCREENSHOT_RETENTION} -type f -iname "*.jpg" -delete >/dev/null 2>&1
 #	echo -n "images; " && find /data/imagecache             -maxdepth 1 -mmin +${PHOTOS_RETENTION}     -type f -iname "*.jpg" -delete >/dev/null 2>&1
 #	echo -n "stuck lock file (if it exists); " && find /run  -maxdepth 1 -mmin +${LOCKFILE_RETENTION}     -type f -iname "vesseldb.lock" -delete >/dev/null 2>&1
 
-	# iterate through the vessels and clean up the old ones:
+# iterate through the vessels and clean up the old ones:
 
-	# get VESSEL data:
-	source "${VESSELDBFILE}"
+# get VESSEL data:
+source "${VESSELDBFILE}"
 #	echo -n "obsolete vessels: "
-        removed=()
-	for mmsi in "${VESSEL_INDEX[@]}"
-	do
-		if [[ -z "${VESSELS[${mmsi}:last_updated]}" ]] || (( $(date +%s) - ${VESSELS[${mmsi}:last_updated]} > MMSI_RETENTION ))
-		then
-#			echo -n "${mmsi} "
-			removed+=(${mmsi})
-			for key in "${KEY_INDEX[@]}"
-			do
-				unset "VESSELS[$mmsi:$key]"
-			done
-			for i in "${!VESSEL_INDEX[@]}"
-			do
-    			if [[ "${VESSEL_INDEX[$i]}" == "${mmsi}" ]]
-				then
-					unset "VESSEL_INDEX[$i]"
-					break
-				fi
-			done
-		fi
-	done
+	removed=()
+for mmsi in "${VESSEL_INDEX[@]}"
+do
+	if [[ -z "${VESSELS[${mmsi}:last_updated]}" ]] || (( $(date +%s) - ${VESSELS[${mmsi}:last_updated]} > MMSI_RETENTION ))
+	then
+#			echo -n "${mmsi} "å
+		removed+=(${mmsi})
+		for key in "${KEY_INDEX[@]}"
+		do
+			unset "VESSELS[$mmsi:$key]"
+		done
+		for i in "${!VESSEL_INDEX[@]}"
+		do
+			if [[ "${VESSEL_INDEX[$i]}" == "${mmsi}" ]]
+			then
+				unset "VESSEL_INDEX[$i]"
+				break
+			fi
+		done
+	fi
+done
 #	echo ""
 
-	# write data back to file:
-	source "/usr/share/vesselalert/save_databases"
-	rm -f "$VESSELDBLOCK"
+# write data back to file:
+source "/usr/share/vesselalert/save_databases"
+rm -f "$VESSELDBLOCK"
 
-	echo -n "[$(date)][$APPNAME] Cleanup finished. Next cleanup run at $(date -d @$(( $(date +%s) + CLEANUP_EVERY )) ). "
-	(( ${#removed[@]} > 0 )) && echo "Removed vessels ${removed[@]}" || echo ""
-	sleep "${CLEANUP_EVERY}"
-done
+echo -n "[$(date)][$APPNAME] Cleanup finished. Next cleanup run at $(date -d @$(( $(date +%s) + CLEANUP_EVERY )) ). "
+(( ${#removed[@]} > 0 )) && echo "Removed vessels ${removed[@]}" || echo ""
+sleep "${CLEANUP_EVERY}"
