major cleanup update

diff --git a/rootfs/etc/services.d/cleanup/run b/rootfs/etc/services.d/cleanup/run
--- a/rootfs/etc/services.d/cleanup/run
+++ b/rootfs/etc/services.d/cleanup/run
@@ -1,5 +1,5 @@
 #!/usr/bin/with-contenv bash
-#shellcheck shell=bash
+#shellcheck shell=bash disable=SC1090,SC1091,SC2015
 
 # Cleanupt:
 # clean up old files
@@ -35,13 +35,47 @@ CLEANUP_EVERY=1800			# every 30 minutes
 PHOTOS_RETENTION=10080 		# time in minutes; 10080 = 1 week
 SCREENSHOT_RETENTION=3600	# 1 hour
 LOCKFILE_RETENTION=1800		# 15 minutes
+MMSI_RETENTION=1209600		# 2 weeks in seconds
+[[ -z "${VESSELDBFILE}" ]] && VESSELDBFILE="/data/vessel.db" || true
+[[ -z "${VESSELDBLOCK}" ]] && VESSELDBLOCK="/run/vesseldb.lock" || true
+
 
 while true
 do
-	echo "[$(date)][$APPNAME] Cleanup performed"
-	find /data/imagecache/screenshots -maxdepth 1 -mmin +${SCREENSHOT_RETENTION} -type f -iname "*.jpg" -delete >/dev/null 2>&1
-	find /data/imagecache             -maxdepth 1 -mmin +${PHOTOS_RETENTION}     -type f -iname "*.jpg" -delete >/dev/null 2>&1
-	find /run  -maxdepth 1 -mmin +${LOCKFILE_RETENTION}     -type f -iname "vesseldb.lock" -delete >/dev/null 2>&1
+	echo "[$(date)][$APPNAME] Starting Cleanup"
+	[[ -f  $VESSELDBLOCK ]] && echo "[$(date)][$APPNAME] Waiting for vessel.db to become unlocked..."
+	while [[ -f  $VESSELDBLOCK ]]
+	do
+		sleep "0.$((RANDOM % 100))"
+	done
+	# Now lock the process for myself:
+    touch "$VESSELDBLOCK"
 
+	echo -n "[$(date)][$APPNAME] Removing obsolete screenshots; " && find /data/imagecache/screenshots -maxdepth 1 -mmin +${SCREENSHOT_RETENTION} -type f -iname "*.jpg" -delete >/dev/null 2>&1
+	echo -n "images; " && find /data/imagecache             -maxdepth 1 -mmin +${PHOTOS_RETENTION}     -type f -iname "*.jpg" -delete >/dev/null 2>&1
+	echo -n "stuck lock file (if it exists); " && find /run  -maxdepth 1 -mmin +${LOCKFILE_RETENTION}     -type f -iname "vesseldb.lock" -delete >/dev/null 2>&1
+
+	# iterate through the vessels and clean up the old ones:
+
+	# get VESSEL data:
+	source "${VESSELDBFILE}"
+	echo -n "obsolete vessels: "
+	for mmsi in "${VESSEL_INDEX[@]}"
+	do
+		if [[ -z "${VESSELS[${mmsi}:last_updated]}" ]] || (( $(date +%s) - ${VESSELS[${mmsi}:last_updated]} > MMSI_RETENTION ))
+		then
+			echo "${mmsi} "
+			for key in "${KEY_INDEX[@]}"
+			do
+				unset "VESSELS[$mmsi:$key]"
+			done
+		fi
+	done
+	echo ""
+
+	# write data back to file:
+	source "/usr/share/vesselalert/save_databases"
+
+	echo "[$(date)][$APPNAME] Cleanup finished. Next cleanup run at $(date -d @$(( $(date +%s) + CLEANUP_EVERY )) )"
 	sleep "${CLEANUP_EVERY}"
 done
